### ISSUE TITLE
Outdated docker image

### ISSUE THREAD

**Issue by mukulhase** [KyleBanks/tensorflow-docker-retrain#3]
https://github.com/KyleBanks/tensorflow-docker-retrain/blob/b53329510726218c56a3aebfbe63085138adedbe/train-classifier/Dockerfile#L1
![image](https://user-images.githubusercontent.com/9693405/47424560-8eca5300-d7a5-11e8-8b77-985bd64f66ad.png)

**Comment by KyleBanks** [comment]
Resolved by #4
